using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MyMathFunctions;

namespace _012_Highly_Divisible_Triangular_Number
{
    class Program
    {
        static void Main(string[] args)
        {
            //The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

            //1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

            //Let us list the factors of the first seven triangle numbers:

            //     1: 1
            //     3: 1,3
            //     6: 1,2,3,6
            //    10: 1,2,5,10
            //    15: 1,3,5,15
            //    21: 1,3,7,21
            //    28: 1,2,4,7,14,28

            //We can see that 28 is the first triangle number to have over five divisors.

            //What is the value of the first triangle number to have over five hundred divisors?

            int numFactors = 1;
            int triangleNumber = 1;
            int i = 1;

            while (numFactors <= 500)
            {
                i++;
                triangleNumber += i;
                numFactors = MathFunctions.NumberOfDivisors(triangleNumber);
            }

            Console.WriteLine("Triangle Number {0} is {1} and has {2} divisors", i, triangleNumber, numFactors);
            Console.Read();


            //answer: 76576500
        }
    }
}
